<?php

namespace Striide\GeoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GeoIpHarvestingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoIpHarvestingRepository extends EntityRepository
{
  public function findOldest()
  {
    $query = $this->getEntityManager()->createQuery('
					SELECT h
					FROM Striide\GeoBundle\Entity\GeoIpHarvesting h
          ORDER BY h.id
				')->setMaxResults(1);
    try
    {
      $ip = $query->getSingleResult();
      return $ip;
    }
    catch(\Doctrine\ORM\NoResultException $e)
    {
      return null;
    }
  }
}
