<?php

namespace Striide\GeoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GeoIPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeoIPRepository extends EntityRepository
{
  /**
   *
   */
  public function findOneByIp($ip)
  {
    $query = $this->getEntityManager()->createQuery('
					SELECT g
					FROM Striide\GeoBundle\Entity\GeoIP g
					WHERE g.ip = :ip
				');
    try
    {
      $query->setParameter('ip',$ip);
      $geoip = $query->getSingleResult();
      return $geoip;
    }
    catch(\Doctrine\ORM\NoResultException $e)
    {
      return null;
    }
  }
}
