<?php
namespace Striide\GeoBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * PostalCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class PostalCodeRepository extends EntityRepository
{
}
