<?php
namespace Striide\GeoBundle\Entity;
use Doctrine\ORM\Query;
use Doctrine\ORM\EntityRepository;
/**
 * ZcuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ZcuRepository extends EntityRepository
{
  public function findZcuArrayByZip($zip) 
  {
    $query = $this->getEntityManager()->createQuery('
					SELECT z
					FROM Striide\GeoBundle\Entity\Zcu z
					WHERE z.zip = :zip
				');
    $query->setParameter('zip', $zip);
    $query->setMaxResults(1);
    $query->useResultCache(true, 1, sprintf('striide_find_zcu_zip_%s', $zip));
    try
    {
      $zcu = $query->getSingleResult(Query::HYDRATE_ARRAY);
      return $zcu;
    }
    catch(\Doctrine\ORM\NoResultException $e) 
    {
      return null;
    }
  }
}
