<?php
namespace Striide\GeoBundle\DataFixtures\ORM;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Striide\GeoBundle\Entity\Countries;

class LoadCountryData extends AbstractFixture implements OrderedFixtureInterface
{
  private function setCountry($manager,$name)
  {
    $c = new Countries();
    $c->setName($name);
    $manager->persist($c);
  }

  public function load(ObjectManager $manager)
  {
    $this->setCountry($manager,"Canada");
    $this->setCountry($manager,"United States");
    $this->setCountry($manager,"Afghanistan");
    $this->setCountry($manager,"Albania");
    $this->setCountry($manager,"Algeria");
    $this->setCountry($manager,"American Samoa");
    $this->setCountry($manager,"Andorra");
    $this->setCountry($manager,"Angola");
    $this->setCountry($manager,"Anguilla");
    $this->setCountry($manager,"Antarctica");
    $this->setCountry($manager,"Antigua And Barbuda");
    $this->setCountry($manager,"Argentina");
    $this->setCountry($manager,"Armenia");
    $this->setCountry($manager,"Aruba");
    $this->setCountry($manager,"Australia");
    $this->setCountry($manager,"Austria");
    $this->setCountry($manager,"Azerbaijan");
    $this->setCountry($manager,"Bahamas");
    $this->setCountry($manager,"Bahrain");
    $this->setCountry($manager,"Bangladesh");
    $this->setCountry($manager,"Barbados");
    $this->setCountry($manager,"Belarus");
    $this->setCountry($manager,"Belgium");
    $this->setCountry($manager,"Belize");
    $this->setCountry($manager,"Benin");
    $this->setCountry($manager,"Bermuda");
    $this->setCountry($manager,"Bhutan");
    $this->setCountry($manager,"Bolivia");
    $this->setCountry($manager,"Bosnia and Herzegowina");
    $this->setCountry($manager,"Botswana");
    $this->setCountry($manager,"Bouvet Island");
    $this->setCountry($manager,"Brazil");
    $this->setCountry($manager,"British Indian Ocean Territory");
    $this->setCountry($manager,"Brunei Darussalam");
    $this->setCountry($manager,"Bulgaria");
    $this->setCountry($manager,"Burkina Faso");
    $this->setCountry($manager,"Burma");
    $this->setCountry($manager,"Burundi");
    $this->setCountry($manager,"Cambodia");
    $this->setCountry($manager,"Cameroon");
    $this->setCountry($manager,"Cape Verde");
    $this->setCountry($manager,"Cayman Islands");
    $this->setCountry($manager,"Central African Republic");
    $this->setCountry($manager,"Chad");
    $this->setCountry($manager,"Chile");
    $this->setCountry($manager,"China");
    $this->setCountry($manager,"Christmas Island");
    $this->setCountry($manager,"Cocos (Keeling) Islands");
    $this->setCountry($manager,"Colombia");
    $this->setCountry($manager,"Comoros");
    $this->setCountry($manager,"Congo");
    $this->setCountry($manager,"Congo, the Democratic Republic of the");
    $this->setCountry($manager,"Cook Islands");
    $this->setCountry($manager,"Costa Rica");
    $this->setCountry($manager,"Cote d'Ivoire");
    $this->setCountry($manager,"Croatia");
    $this->setCountry($manager,"Cuba");
    $this->setCountry($manager,"Cyprus");
    $this->setCountry($manager,"Czech Republic");
    $this->setCountry($manager,"Denmark");
    $this->setCountry($manager,"Djibouti");
    $this->setCountry($manager,"Dominica");
    $this->setCountry($manager,"Dominican Republic");
    $this->setCountry($manager,"East Timor");
    $this->setCountry($manager,"Ecuador");
    $this->setCountry($manager,"Egypt");
    $this->setCountry($manager,"El Salvador");
    $this->setCountry($manager,"England");
    $this->setCountry($manager,"Equatorial Guinea");
    $this->setCountry($manager,"Eritrea");
    $this->setCountry($manager,"Espana");
    $this->setCountry($manager,"Estonia");
    $this->setCountry($manager,"Ethiopia");
    $this->setCountry($manager,"Falkland Islands");
    $this->setCountry($manager,"Faroe Islands");
    $this->setCountry($manager,"Fiji");
    $this->setCountry($manager,"Finland");
    $this->setCountry($manager,"France");
    $this->setCountry($manager,"French Guiana");
    $this->setCountry($manager,"French Polynesia");
    $this->setCountry($manager,"French Southern Territories");
    $this->setCountry($manager,"Gabon");
    $this->setCountry($manager,"Gambia");
    $this->setCountry($manager,"Georgia");
    $this->setCountry($manager,"Germany");
    $this->setCountry($manager,"Ghana");
    $this->setCountry($manager,"Gibraltar");
    $this->setCountry($manager,"Great Britain");
    $this->setCountry($manager,"Greece");
    $this->setCountry($manager,"Greenland");
    $this->setCountry($manager,"Grenada");
    $this->setCountry($manager,"Guadeloupe");
    $this->setCountry($manager,"Guam");
    $this->setCountry($manager,"Guatemala");
    $this->setCountry($manager,"Guinea");
    $this->setCountry($manager,"Guinea-Bissau");
    $this->setCountry($manager,"Guyana");
    $this->setCountry($manager,"Haiti");
    $this->setCountry($manager,"Heard and Mc Donald Islands");
    $this->setCountry($manager,"Honduras");
    $this->setCountry($manager,"Hong Kong");
    $this->setCountry($manager,"Hungary");
    $this->setCountry($manager,"Iceland");
    $this->setCountry($manager,"India");
    $this->setCountry($manager,"Indonesia");
    $this->setCountry($manager,"Ireland");
    $this->setCountry($manager,"Israel");
    $this->setCountry($manager,"Italy");
    $this->setCountry($manager,"Iran");
    $this->setCountry($manager,"Iraq");
    $this->setCountry($manager,"Jamaica");
    $this->setCountry($manager,"Japan");
    $this->setCountry($manager,"Jordan");
    $this->setCountry($manager,"Kazakhstan");
    $this->setCountry($manager,"Kenya");
    $this->setCountry($manager,"Kiribati");
    $this->setCountry($manager,"Korea, Republic of");
    $this->setCountry($manager,"Korea (South)");
    $this->setCountry($manager,"Kuwait");
    $this->setCountry($manager,"Kyrgyzstan");
    $this->setCountry($manager,"Lao People's Democratic Republic");
    $this->setCountry($manager,"Latvia");
    $this->setCountry($manager,"Lebanon");
    $this->setCountry($manager,"Lesotho");
    $this->setCountry($manager,"Liberia");
    $this->setCountry($manager,"Liechtenstein");
    $this->setCountry($manager,"Lithuania");
    $this->setCountry($manager,"Luxembourg");
    $this->setCountry($manager,"Macau");
    $this->setCountry($manager,"Macedonia");
    $this->setCountry($manager,"Madagascar");
    $this->setCountry($manager,"Malawi");
    $this->setCountry($manager,"Malaysia");
    $this->setCountry($manager,"Maldives");
    $this->setCountry($manager,"Mali");
    $this->setCountry($manager,"Malta");
    $this->setCountry($manager,"Marshall Islands");
    $this->setCountry($manager,"Martinique");
    $this->setCountry($manager,"Mauritania");
    $this->setCountry($manager,"Mauritius");
    $this->setCountry($manager,"Mayotte");
    $this->setCountry($manager,"Mexico");
    $this->setCountry($manager,"Micronesia, Federated States of");
    $this->setCountry($manager,"Moldova, Republic of");
    $this->setCountry($manager,"Monaco");
    $this->setCountry($manager,"Mongolia");
    $this->setCountry($manager,"Montserrat");
    $this->setCountry($manager,"Morocco");
    $this->setCountry($manager,"Mozambique");
    $this->setCountry($manager,"Myanmar");
    $this->setCountry($manager,"Namibia");
    $this->setCountry($manager,"Nauru");
    $this->setCountry($manager,"Nepal");
    $this->setCountry($manager,"Netherlands");
    $this->setCountry($manager,"Netherlands Antilles");
    $this->setCountry($manager,"New Caledonia");
    $this->setCountry($manager,"New Zealand");
    $this->setCountry($manager,"Nicaragua");
    $this->setCountry($manager,"Niger");
    $this->setCountry($manager,"Nigeria");
    $this->setCountry($manager,"Niue");
    $this->setCountry($manager,"Norfolk Island");
    $this->setCountry($manager,"Northern Ireland");
    $this->setCountry($manager,"Northern Mariana Islands");
    $this->setCountry($manager,"Norway");
    $this->setCountry($manager,"Oman");
    $this->setCountry($manager,"Pakistan");
    $this->setCountry($manager,"Palau");
    $this->setCountry($manager,"Panama");
    $this->setCountry($manager,"Papua New Guinea");
    $this->setCountry($manager,"Paraguay");
    $this->setCountry($manager,"Peru");
    $this->setCountry($manager,"Philippines");
    $this->setCountry($manager,"Pitcairn");
    $this->setCountry($manager,"Poland");
    $this->setCountry($manager,"Portugal");
    $this->setCountry($manager,"Puerto Rico");
    $this->setCountry($manager,"Qatar");
    $this->setCountry($manager,"Reunion");
    $this->setCountry($manager,"Romania");
    $this->setCountry($manager,"Russia");
    $this->setCountry($manager,"Rwanda");
    $this->setCountry($manager,"Saint Kitts and Nevis");
    $this->setCountry($manager,"Saint Lucia");
    $this->setCountry($manager,"Saint Vincent and the Grenadines");
    $this->setCountry($manager,"Samoa (Independent)");
    $this->setCountry($manager,"San Marino");
    $this->setCountry($manager,"Sao Tome and Principe");
    $this->setCountry($manager,"Saudi Arabia");
    $this->setCountry($manager,"Scotland");
    $this->setCountry($manager,"Senegal");
    $this->setCountry($manager,"Serbia and Montenegro");
    $this->setCountry($manager,"Seychelles");
    $this->setCountry($manager,"Sierra Leone");
    $this->setCountry($manager,"Singapore");
    $this->setCountry($manager,"Slovakia");
    $this->setCountry($manager,"Slovenia");
    $this->setCountry($manager,"Solomon Islands");
    $this->setCountry($manager,"Somalia");
    $this->setCountry($manager,"South Africa");
    $this->setCountry($manager,"South Georgia and the South Sandwich Islands");
    $this->setCountry($manager,"South Korea");
    $this->setCountry($manager,"Spain");
    $this->setCountry($manager,"Sri Lanka");
    $this->setCountry($manager,"St. Helena");
    $this->setCountry($manager,"St. Pierre and Miquelon");
    $this->setCountry($manager,"Suriname");
    $this->setCountry($manager,"Svalbard and Jan Mayen Islands");
    $this->setCountry($manager,"Swaziland");
    $this->setCountry($manager,"Sweden");
    $this->setCountry($manager,"Switzerland");
    $this->setCountry($manager,"Taiwan");
    $this->setCountry($manager,"Tajikistan");
    $this->setCountry($manager,"Tanzania");
    $this->setCountry($manager,"Thailand");
    $this->setCountry($manager,"Togo");
    $this->setCountry($manager,"Tokelau");
    $this->setCountry($manager,"Tonga");
    $this->setCountry($manager,"Trinidad");
    $this->setCountry($manager,"Trinidad and Tobago");
    $this->setCountry($manager,"Tunisia");
    $this->setCountry($manager,"Turkey");
    $this->setCountry($manager,"Turkmenistan");
    $this->setCountry($manager,"Turks and Caicos Islands");
    $this->setCountry($manager,"Tuvalu");
    $this->setCountry($manager,"Uganda");
    $this->setCountry($manager,"Ukraine");
    $this->setCountry($manager,"United Arab Emirates");
    $this->setCountry($manager,"United Kingdom");
    $this->setCountry($manager,"United States Minor Outlying Islands");
    $this->setCountry($manager,"Uruguay");
    $this->setCountry($manager,"Uzbekistan");
    $this->setCountry($manager,"Vanuatu");
    $this->setCountry($manager,"Vatican City State (Holy See)");
    $this->setCountry($manager,"Venezuela");
    $this->setCountry($manager,"Viet Nam");
    $this->setCountry($manager,"Virgin Islands (British)");
    $this->setCountry($manager,"Virgin Islands (U.S.)");
    $this->setCountry($manager,"Wales");
    $this->setCountry($manager,"Wallis and Futuna Islands");
    $this->setCountry($manager,"Western Sahara");
    $this->setCountry($manager,"Yemen");
    $this->setCountry($manager,"Zambia");
    $this->setCountry($manager,"Zimbabwe");
    $manager->flush();
  }
  public function getOrder()
  {
    return 1;
  }
}
